#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5CC908FDB71E12C2 (daniel@haxx.se)
#
Name     : c-ares
Version  : 1.15.0
Release  : 14
URL      : http://c-ares.haxx.se/download/c-ares-1.15.0.tar.gz
Source0  : http://c-ares.haxx.se/download/c-ares-1.15.0.tar.gz
Source99 : http://c-ares.haxx.se/download/c-ares-1.15.0.tar.gz.asc
Summary  : asynchronous DNS lookup library
Group    : Development/Tools
License  : GPL-2.0+ MIT X11
Requires: c-ares-lib = %{version}-%{release}
Requires: c-ares-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
Patch1: defaults.patch

%description
___       __ _ _ __ ___  ___
/ __| ___ / _` | '__/ _ \/ __|
| (_  |___| (_| | | |  __/\__ \
\___|     \__,_|_|  \___||___/

%package dev
Summary: dev components for the c-ares package.
Group: Development
Requires: c-ares-lib = %{version}-%{release}
Provides: c-ares-devel = %{version}-%{release}

%description dev
dev components for the c-ares package.


%package lib
Summary: lib components for the c-ares package.
Group: Libraries
Requires: c-ares-license = %{version}-%{release}

%description lib
lib components for the c-ares package.


%package license
Summary: license components for the c-ares package.
Group: Default

%description license
license components for the c-ares package.


%prep
%setup -q -n c-ares-1.15.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1544654291
%reconfigure --disable-static
make  %{?_smp_mflags} DEFAULTFLAGS="$CFLAGS"

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1544654291
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/c-ares
cp LICENSE.md %{buildroot}/usr/share/package-licenses/c-ares/LICENSE.md
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libcares.so
/usr/lib64/pkgconfig/libcares.pc
/usr/share/man/man3/ares_cancel.3
/usr/share/man/man3/ares_create_query.3
/usr/share/man/man3/ares_destroy.3
/usr/share/man/man3/ares_destroy_options.3
/usr/share/man/man3/ares_dup.3
/usr/share/man/man3/ares_expand_name.3
/usr/share/man/man3/ares_expand_string.3
/usr/share/man/man3/ares_fds.3
/usr/share/man/man3/ares_free_data.3
/usr/share/man/man3/ares_free_hostent.3
/usr/share/man/man3/ares_free_string.3
/usr/share/man/man3/ares_get_servers.3
/usr/share/man/man3/ares_get_servers_ports.3
/usr/share/man/man3/ares_gethostbyaddr.3
/usr/share/man/man3/ares_gethostbyname.3
/usr/share/man/man3/ares_gethostbyname_file.3
/usr/share/man/man3/ares_getnameinfo.3
/usr/share/man/man3/ares_getsock.3
/usr/share/man/man3/ares_inet_ntop.3
/usr/share/man/man3/ares_inet_pton.3
/usr/share/man/man3/ares_init.3
/usr/share/man/man3/ares_init_options.3
/usr/share/man/man3/ares_library_cleanup.3
/usr/share/man/man3/ares_library_init.3
/usr/share/man/man3/ares_library_init_android.3
/usr/share/man/man3/ares_library_initialized.3
/usr/share/man/man3/ares_mkquery.3
/usr/share/man/man3/ares_parse_a_reply.3
/usr/share/man/man3/ares_parse_aaaa_reply.3
/usr/share/man/man3/ares_parse_mx_reply.3
/usr/share/man/man3/ares_parse_naptr_reply.3
/usr/share/man/man3/ares_parse_ns_reply.3
/usr/share/man/man3/ares_parse_ptr_reply.3
/usr/share/man/man3/ares_parse_soa_reply.3
/usr/share/man/man3/ares_parse_srv_reply.3
/usr/share/man/man3/ares_parse_txt_reply.3
/usr/share/man/man3/ares_process.3
/usr/share/man/man3/ares_query.3
/usr/share/man/man3/ares_save_options.3
/usr/share/man/man3/ares_search.3
/usr/share/man/man3/ares_send.3
/usr/share/man/man3/ares_set_local_dev.3
/usr/share/man/man3/ares_set_local_ip4.3
/usr/share/man/man3/ares_set_local_ip6.3
/usr/share/man/man3/ares_set_servers.3
/usr/share/man/man3/ares_set_servers_csv.3
/usr/share/man/man3/ares_set_servers_ports.3
/usr/share/man/man3/ares_set_servers_ports_csv.3
/usr/share/man/man3/ares_set_socket_callback.3
/usr/share/man/man3/ares_set_socket_configure_callback.3
/usr/share/man/man3/ares_set_socket_functions.3
/usr/share/man/man3/ares_set_sortlist.3
/usr/share/man/man3/ares_strerror.3
/usr/share/man/man3/ares_timeout.3
/usr/share/man/man3/ares_version.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcares.so.2
/usr/lib64/libcares.so.2.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/c-ares/LICENSE.md
